"""Оплата пользования

Revision ID: 2ad24f827e45
Revises: 8911511c51c5
Create Date: 2026-09-23 22:15:34.346557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad24f827e45'
down_revision: Union[str, Sequence[str], None] = '8911511c51c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('period_from', sa.DateTime(), nullable=True),
    sa.Column('period_to', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_payments_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_payments_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_payments_paid_at'), ['paid_at'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('block_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('block_reason')
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('plan')

    with op.batch_alter_table('account_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_account_payments_external_id'))
        batch_op.drop_index(batch_op.f('ix_account_payments_account_id'))

    op.drop_table('account_payments')
    # ### end Alembic commands ###
