"""Напоминания клиенту в Telegram

Revision ID: 5253850f9b95
Revises: 2ad24f827e45
Create Date: 2026-09-26 16:49:54.870037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5253850f9b95'
down_revision: Union[str, Sequence[str], None] = '2ad24f827e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('about', sa.String(length=20), nullable=True),
    sa.Column('about_id', sa.Integer(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_about_id'), ['about_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_notices_due', ['state', 'send_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_send_at'), ['send_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_state'), ['state'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_bot_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram_bot_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_secret', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_telegram_secret'), ['telegram_secret'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('telegram_linked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('telegram_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('telegram_code_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_telegram_code'), ['telegram_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_telegram_code'))
        batch_op.drop_index(batch_op.f('ix_clients_telegram_chat_id'))
        batch_op.drop_column('telegram_code_until')
        batch_op.drop_column('telegram_code')
        batch_op.drop_column('telegram_linked_at')
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_telegram_secret'))
        batch_op.drop_column('telegram_secret')
        batch_op.drop_column('telegram_bot_username')
        batch_op.drop_column('telegram_bot_token')

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_state'))
        batch_op.drop_index(batch_op.f('ix_notices_send_at'))
        batch_op.drop_index(batch_op.f('ix_notices_kind'))
        batch_op.drop_index('ix_notices_due')
        batch_op.drop_index(batch_op.f('ix_notices_client_id'))
        batch_op.drop_index(batch_op.f('ix_notices_account_id'))
        batch_op.drop_index(batch_op.f('ix_notices_about_id'))

    op.drop_table('notices')
    # ### end Alembic commands ###
