"""Начальная схема

Revision ID: 8911511c51c5
Revises: 
Create Date: 2026-09-23 21:55:47.039441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8911511c51c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_slug'), ['slug'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('pin_updated_at', sa.DateTime(), nullable=True),
    sa.Column('pin_failures', sa.Integer(), nullable=False),
    sa.Column('pin_blocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'local_id', name='uq_clients_account_local'),
    sa.UniqueConstraint('account_id', 'phone', name='uq_clients_account_phone')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_phone'), ['phone'], unique=False)

    op.create_table('login_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_codes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_codes_login'), ['login'], unique=False)
        batch_op.create_index('ix_login_codes_login_created', ['login', 'created_at'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sync_key_hash', sa.String(length=255), nullable=True),
    sa.Column('sync_key_set_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_shops_sync_key_hash'), ['sync_key_hash'], unique=False)

    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_updated_at', sa.DateTime(), nullable=True),
    sa.Column('pin_failures', sa.Integer(), nullable=False),
    sa.Column('pin_blocked_at', sa.DateTime(), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('access_changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'phone', name='uq_staff_users_account_phone')
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_phone'), ['phone'], unique=False)

    op.create_table('booking_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.String(length=5), nullable=True),
    sa.Column('closes_at', sa.String(length=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'day', name='uq_booking_days_shop_day')
    )
    with op.batch_alter_table('booking_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_days_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_days_shop_id'), ['shop_id'], unique=False)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('wheel_diameter', sa.String(length=10), nullable=True),
    sa.Column('wheels_assembled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_local_id'), ['local_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('pin_failures', sa.Integer(), nullable=False),
    sa.Column('pin_blocked_at', sa.DateTime(), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_push_token'), ['push_token'], unique=False)

    op.create_table('queue_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('cars_in_work', sa.Integer(), nullable=False),
    sa.Column('cars_waiting', sa.Integer(), nullable=False),
    sa.Column('open_posts', sa.Integer(), nullable=False),
    sa.Column('free_in_minutes', sa.Integer(), nullable=True),
    sa.Column('shift_is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_snapshots_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_snapshots_taken_at'), ['taken_at'], unique=False)

    op.create_table('salary_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('employee_local_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('is_advance', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sync_state', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_salary_payouts_shop_local')
    )
    with op.batch_alter_table('salary_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_payouts_employee_local_id'), ['employee_local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_payouts_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_payouts_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_payouts_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_payouts_sync_state'), ['sync_state'], unique=False)

    op.create_table('shop_employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('salary_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_shop_employees_shop_local')
    )
    with op.batch_alter_table('shop_employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_employees_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_employees_shop_id'), ['shop_id'], unique=False)

    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'key', name='uq_shop_settings_shop_key')
    )
    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_settings_shop_id'), ['shop_id'], unique=False)

    op.create_table('shop_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('open_posts', sa.Integer(), nullable=False),
    sa.Column('total_salary', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_shop_shifts_shop_local')
    )
    with op.batch_alter_table('shop_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_shifts_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_shifts_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_shifts_started_at'), ['started_at'], unique=False)

    op.create_table('staff_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_actions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_actions_happened_at'), ['happened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_actions_staff_id'), ['staff_id'], unique=False)

    op.create_table('stored_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('wheel_type', sa.String(length=50), nullable=True),
    sa.Column('diameter', sa.String(length=10), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_for', sa.DateTime(), nullable=True),
    sa.Column('request_state', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_stored_sets_shop_local')
    )
    with op.batch_alter_table('stored_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_sets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_sets_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_sets_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_sets_request_state'), ['request_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_sets_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_sets_status'), ['status'], unique=False)

    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('shift_local_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('wheel_diameter', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('consumables_amount', sa.Float(), nullable=False),
    sa.Column('salary_base', sa.Float(), nullable=False),
    sa.Column('general_discount', sa.Integer(), nullable=False),
    sa.Column('rim_discount', sa.Integer(), nullable=False),
    sa.Column('auto_discount', sa.Boolean(), nullable=False),
    sa.Column('refunded_amount', sa.Float(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_type', sa.String(length=20), nullable=True),
    sa.Column('refund_reason', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_visits_shop_local')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index('ix_visits_client_date', ['client_id', 'visited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_refunded_at'), ['refunded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_shift_local_id'), ['shift_local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visited_at'), ['visited_at'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('wheels_assembled', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sync_state', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'local_id', name='uq_appointments_shop_local')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_sync_state'), ['sync_state'], unique=False)

    op.create_table('salary_accruals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('employee_local_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('accrued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_accruals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_accruals_accrued_at'), ['accrued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_accruals_employee_local_id'), ['employee_local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_accruals_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('consumable_cost', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_items_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_items_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_items_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_items_local_id'))

    op.drop_table('visit_items')
    with op.batch_alter_table('salary_accruals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_accruals_visit_id'))
        batch_op.drop_index(batch_op.f('ix_salary_accruals_employee_local_id'))
        batch_op.drop_index(batch_op.f('ix_salary_accruals_accrued_at'))

    op.drop_table('salary_accruals')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_sync_state'))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_shop_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_local_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_license_plate'))
        batch_op.drop_index(batch_op.f('ix_appointments_client_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visited_at'))
        batch_op.drop_index(batch_op.f('ix_visits_shop_id'))
        batch_op.drop_index(batch_op.f('ix_visits_shift_local_id'))
        batch_op.drop_index(batch_op.f('ix_visits_refunded_at'))
        batch_op.drop_index(batch_op.f('ix_visits_local_id'))
        batch_op.drop_index(batch_op.f('ix_visits_license_plate'))
        batch_op.drop_index(batch_op.f('ix_visits_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_visits_client_id'))
        batch_op.drop_index('ix_visits_client_date')
        batch_op.drop_index(batch_op.f('ix_visits_changed_at'))

    op.drop_table('visits')
    with op.batch_alter_table('stored_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_sets_status'))
        batch_op.drop_index(batch_op.f('ix_stored_sets_shop_id'))
        batch_op.drop_index(batch_op.f('ix_stored_sets_request_state'))
        batch_op.drop_index(batch_op.f('ix_stored_sets_local_id'))
        batch_op.drop_index(batch_op.f('ix_stored_sets_license_plate'))
        batch_op.drop_index(batch_op.f('ix_stored_sets_client_id'))

    op.drop_table('stored_sets')
    with op.batch_alter_table('staff_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_actions_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_actions_happened_at'))
        batch_op.drop_index(batch_op.f('ix_staff_actions_account_id'))

    op.drop_table('staff_actions')
    with op.batch_alter_table('shop_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_shifts_started_at'))
        batch_op.drop_index(batch_op.f('ix_shop_shifts_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_shifts_local_id'))

    op.drop_table('shop_shifts')
    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_settings_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_settings_key'))

    op.drop_table('shop_settings')
    with op.batch_alter_table('shop_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_employees_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_employees_local_id'))

    op.drop_table('shop_employees')
    with op.batch_alter_table('salary_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_payouts_sync_state'))
        batch_op.drop_index(batch_op.f('ix_salary_payouts_shop_id'))
        batch_op.drop_index(batch_op.f('ix_salary_payouts_paid_at'))
        batch_op.drop_index(batch_op.f('ix_salary_payouts_local_id'))
        batch_op.drop_index(batch_op.f('ix_salary_payouts_employee_local_id'))

    op.drop_table('salary_payouts')
    with op.batch_alter_table('queue_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_snapshots_taken_at'))
        batch_op.drop_index(batch_op.f('ix_queue_snapshots_shop_id'))

    op.drop_table('queue_snapshots')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_push_token'))
        batch_op.drop_index(batch_op.f('ix_devices_device_id'))
        batch_op.drop_index(batch_op.f('ix_devices_client_id'))

    op.drop_table('devices')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_local_id'))
        batch_op.drop_index(batch_op.f('ix_cars_license_plate'))
        batch_op.drop_index(batch_op.f('ix_cars_client_id'))
        batch_op.drop_index(batch_op.f('ix_cars_account_id'))

    op.drop_table('cars')
    with op.batch_alter_table('booking_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_days_shop_id'))
        batch_op.drop_index(batch_op.f('ix_booking_days_day'))

    op.drop_table('booking_days')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_phone'))
        batch_op.drop_index(batch_op.f('ix_staff_users_account_id'))

    op.drop_table('staff_users')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_sync_key_hash'))
        batch_op.drop_index(batch_op.f('ix_shops_slug'))
        batch_op.drop_index(batch_op.f('ix_shops_account_id'))

    op.drop_table('shops')
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_login_codes_login_created')
        batch_op.drop_index(batch_op.f('ix_login_codes_login'))
        batch_op.drop_index(batch_op.f('ix_login_codes_account_id'))

    op.drop_table('login_codes')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_phone'))
        batch_op.drop_index(batch_op.f('ix_clients_local_id'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_account_id'))

    op.drop_table('clients')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_slug'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
