"""Основные услуги и допродажи

Позиция наряда запоминает, была ли услуга допродажей. Именно позиция, а
не услуга в прайсе: разметят прайс иначе — прошлые наряды меняться не
должны, иначе сравнение месяцев перестанет что-либо значить.

Всё существующее остаётся основным. Выдумывать за владельца, что
считать допродажей, нельзя — он разметит прайс сам.

Revision ID: ad3481d53861
Revises: e3f19844115a
Create Date: 2026-10-07 13:15:03.565045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3481d53861'
down_revision: Union[str, Sequence[str], None] = 'e3f19844115a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        # Без значения по умолчанию колонку NOT NULL в таблицу с
        # данными добавить нельзя: у существующих строк она пустая,
        # и база откажет. Всё, что продано раньше, считаем основным
        batch_op.add_column(sa.Column('is_extra', sa.Boolean(),
                                      nullable=False,
                                      server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_visit_items_is_extra'), ['is_extra'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_items_is_extra'))
        batch_op.drop_column('is_extra')

    # ### end Alembic commands ###
