"""Уведомления в браузере

Второй канал напоминаний рядом с телеграмом. Подписка принадлежит
браузеру, а не человеку: с телефона и с компьютера их будет две, и
слать надо во все — неизвестно, что у человека под рукой.

В notices появилась колонка channel: чем именно ушло сообщение. Нужна
не для отправки, а чтобы по журналу было видно, какой канал у людей
на самом деле работает.

Revision ID: e3f19844115a
Revises: 5253850f9b95
Create Date: 2026-09-27 12:26:38.877911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f19844115a'
down_revision: Union[str, Sequence[str], None] = '5253850f9b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'endpoint', name='uq_push_client_point')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_column('channel')

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_client_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_account_id'))

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
